name: TesseractUHC
main: com.martinbrook.tesseractuhc.UhcTools
version: 0.4
description: Useful commands for UHC matches
commands:
 tp:
  description: Teleportation functions
  usage: /tp | /tp player | /tp player destinationplayer | /tp x y z | /tp player x y z
 tpall:
  description: Teleports all non-creative players to you
  usage: /tpall 
 butcher:
  description: Butchers hostile mobs
  usage: /butcher
 tpd:
  description: Teleports to the last death point
  usage: /tpd
 tpl:
  description: Teleports to the last logout location
  usage: /tpl
 tpn:
  description: Teleports to the last notification
  usage: /tpn
 tps:
  description: Teleports to a player's start point
  usage: /tps start-number | playername
 tp0:
  description: Teleports to the overworld spawn point
  usage: /tp0
 setspawn:
  description: Sets the spawn point to your current location
  usage: /setspawn
 gm:
  description: Toggle gamemode between CREATIVE and SURVIVAL.
  usage: /gm
 heal:
  description: Heals a player
  usage: /heal player
 healall:
  description: Heals all players
  usage: /healall
 feed:
  description: Feeds a player
  usage: /feed player
 feedall:
  description: Feeds all players
  usage: /feedall
 clearinv:
  description: Clears a player's inventory
  usage: /clearinv player
 clearinvall:
  description: Clears all players' inventories
  usage: /clearinvall
 renew:
  description: Feeds, heals and clearinvs a player
  usage: /renew player
 renewall:
  description: Renews all players
  usage: /renewall
 match:
  description: Starts the match countdown
  usage: /match seconds
 cdpvp:
  description: Starts the PvP countdown
  usage: /cdpvp seconds
 cdwb:
  description: Starts a world border countdown
  usage: /cdwb newradius seconds
 cdc:
  description: Cancels a running countdown
  usage: /cdc
 chatscript:
  description: Plays a chat script from a file, one line per second
  usage: /chatscript filename
 muteall:
  description: Mutes the chat so that nobody can talk except ops
  usage: /muteall on | off
 pvp:
  description: Enables/disabled PvP
  usage: /pvp on | off
 kill:
  description: Command disabled
  usage: /kill
 notify:
  description: Sends a private notification message to an admin
  usage: /notify Message
  alias: n
 n:
  description: Sends a private notification message to an admin
  usage: /n Message
  alias: notify
 permaday:
  description: Enable/disable permaday
  usage: /permaday on | off
 deathban:
  description: Enable/disable deathban
  usage: /deathban on | off
 uhc:
  description: UHC match configuration commands
  usage: /uhc commandtype parameters
 listplayers:
  description: List all players, and their start points and status
  usage: /listplayers
 launch:
  description: Launch any players who haven't yet been launched
  usage: /launch
 addplayers:
  description: Set start points for all players on the server
  usage: /addplayers
 addplayer:
  description: Set start point for the specified player
  usage: /addplayer player
 removeplayer:
  description: Remove a specific player
  usage: /removeplayer player
 rmplayer:
  description: Remove a specific player
  usage: /rmplayer player
 relaunch:
  description: Relaunch a player
  usage: /relaunch player
 calcstarts:
  description: Calculate potential start points
  usage: /calcstarts type param1 param2
 tpcs:
  description: Teleport to a calculated start point
  usage: /tpcs number
 vi:
  description: View a player's inventory
  usage: /vi player
 pi:
  description: View a player's inventory
  usage: /pi player
 setvanish:
  description: Update vanish status of all players on the server
  usage: /setvanish